[package]
name = "yang2"
version = "0.2.1"
authors = ["Renato Westphal <renato@opensourcerouting.org>"]
description = "libyang2 bindings for Rust"
keywords = ["yang", "libyang"]
edition = "2018"
license = "MIT"
repository = "https://github.com/rwestphal/yang2-rs"
documentation = "https://docs.rs/yang2"
readme = "README.md"
categories = ["parser-implementations"]
exclude = ["assets/**"]

[dependencies]
libyang2-sys = { path = "libyang2-sys", version = "0.2.1" }
bitflags = "1.0"
num-traits = "0.2"
num-derive = "0.3"

[dev-dependencies]
criterion = "0.3.3"

[[bench]]
name = "data"
harness = false

[features]
default = []
use_bindgen = ["libyang2-sys/use_bindgen"]
bundled = ["libyang2-sys/bundled"]
