name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install libyang2
      run: |
        sudo apt-get install cmake libpcre3-dev
        git clone https://github.com/CESNET/libyang.git
        cd libyang
        git checkout 45802b59e0ef479a1af8cf373bb24b50d348bbbd
        mkdir build
        cd build
        cmake -DENABLE_BUILD_TESTS=OFF -DCMAKE_BUILD_TYPE:String="Release" ..
        make
        sudo make install
        sudo ldconfig
    - name: Build
      run: cargo build --features use_bindgen --verbose
    - name: Run tests
      run: cargo test --features use_bindgen --verbose
